#include <iostream>
#include <vector>
#include <functional>
#include <thread>
//#include <mutex>
//#include <condition_variable>
//#include <omp.h>
//#include "utils.cpp"
#include "utimer.cpp"
#include <ff/ff.hpp>